backend:
  name: git-gateway
  repo: owenhoskins/gatsby-sharp-netlify-cms
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/img' # this is where netlify cms places images.
public_folder: '/img' # this is where gatsby places images

collections:

  - name: 'gallery'
    label: 'Gallery'
    folder: 'src/pages/galleries'
    create: true
    slug: '{{slug}}'
    fields:
      - {name: kind, widget: hidden, default: 'gallery'}
      - {label: 'Template', name: 'templateKey', widget: 'hidden', default: gallery }
      - {label: 'Path', name: 'path', widget: 'string', pattern: ['^\/[a-z0-9\-]+$', 'Must begin with "/" and may only consist of lowercase letters (except umlauts), numbers and "-"']}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {name: order, label: Position, widget: number, default: 0}
      - {label: 'Body', name: 'body', widget: 'markdown'}
      - name: images
        label: Gallery
        widget: gallery
        required: true
        fields:
          - {name: image, label: Image, widget: image, class: 'gallery'}