backend:
  name: github
  repo: swartists/starworksartists.com
  branch: development # Branch to update (optional; defaults to master)

media_folder: 'static/img' # this is where netlify cms places images.
public_folder: '/img' # this is where gatsby places images

# publish_mode: editorial_workflow

collections:

  - name: artists
    label: Artists
    folder: 'src/pages/artists'
    slug: '/artists/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {name: kind, widget: hidden, default: 'artist'}
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Type", name: "type", widget: "select", options: ["hair", "makeup", "stylist", "grooming", "manicurist", "special-bookings"]}
      - {label: "Cover Image", name: "cover", widget: "image", tagname: "", optional: true}
      - {label: "Instagram handle", name: "instagram_handle", widget: "string", tagname: "p", required: false}
      - {label: "Enquire", name: "enquire", widget: "string", tagname: "p", required: false}
      - name: portfolios
        label: Portfolios
        widget: list
        optional: true
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Columns', name: 'columns', widget: 'number', min: 3, max: 9}
          - name: gallery
            label: Gallery
            widget: gallery
            required: true
            fields:
              - {name: image, label: Image, widget: image, class: 'gallery'}
              - {name: 'fullscreen', label: 'Fullscreen', widget: 'boolean', default: false }
              - {name: 'focalX', label: 'Focal X', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
              - {name: 'focalY', label: 'Focal Y', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
      - name: videos
        label: Videos
        widget: list
        optional: true
        fields:
          - {label: 'ID', name: 'url', widget: 'number'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Poster', name: 'poster', widget: 'string'}
          - {label: 'Ratio', name: 'ratio', widget: 'string'}
      - {label: "Biography Text", name: "body", widget: "markdown"}

  - name: services
    label: Services
    folder: 'src/pages/services'
    slug: '/services/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text"}


  - name: settings
    label: Settings
    delete: false
    editor:
      preview: false
    files:
      - name: metadata
        label: Global Settings
        file: data/site-metadata.yml
        description: "Settings"
        fields:
          - {label: "Name of website", name: title, widget: "string"}
          - {label: "Google Analytics UA-Code", name: trackingId, widget: "string"}
          - label: "Meta"
            name: meta
            widget: object
            fields:
              - label: Description
                name: description
                widget: text
                required: false
              - label: Keywords
                name: keywords
                widget: text
                required: false

      - name: agency
        label: Agency
        folder: 'data/agency.yml'
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text"}
          - name: contact
            label: Contact
            widget: list
            required: false
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Name, name: name, widget: string}
              - {label: Url, name: url, widget: string}
          - name: addresses
            label: Addresses
            widget: list
            required: false
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Address, name: address, widget: text}




