backend:
  name: git-gateway
  repo: owenhoskins/gatsby-sharp-netlify-cms
  branch: artist-theme # Branch to update (optional; defaults to master)

media_folder: 'static/img' # this is where netlify cms places images.
public_folder: '/img' # this is where gatsby places images

collections:

  - name: artists
    label: Artists
    folder: 'src/pages/artists'
    slug: '/artists/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {name: kind, widget: hidden, default: 'artist'}
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Type", name: "type", widget: "select", options: ["hair", "makeup", "stylist", "grooming", "manicurist", "color"]}
      - {name: order, label: Position, widget: number, default: 0}
      - {label: "Cover Image", name: "cover", widget: "image", required: true, tagname: ""}
      - {label: "Instagram handle", name: "instagram_handle", widget: "string", tagname: "p", required: false}
      - {label: "Enquire", name: "enquire", widget: "string", tagname: "p", required: false}
      - name: portfolios
        label: Portfolios
        widget: list
        optional: true
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: gallery
            label: Gallery
            widget: gallery
            required: true
            fields:
              - {name: image, label: Image, widget: image, class: 'gallery'}
              - {name: 'fullscreen', label: 'Fullscreen', widget: 'boolean', default: false }
              - {name: 'focalX', label: 'Focal X', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
              - {name: 'focalY', label: 'Focal Y', widget: 'number', default: 0, valueType: 'int', min: 0, max: 100}
      - name: videos
        label: Videos
        widget: list
        optional: true
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'URL', name: 'url', widget: 'string'}
      - {label: "Biography Text", name: "body", widget: "markdown"}

  - name: services
    label: Services
    folder: 'src/pages/services'
    slug: '/services/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {name: kind, widget: hidden, default: 'service'}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text"}
